draw_config:
  n_columns: 1
  draw_key_sides: true
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 40.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  svg_extra_style: |
    /* For default sytles, see https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L85 */

    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 12px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
    }

    /* Color accent for held keys */
    rect.held, rect.combo.held {
        fill: #ffc;
    }

    /* Technique borrowed and extended from https://github.com/englmaxi/zmk-config/blob/master/keymap-drawer/config.yaml */
    .sym_sub_text.tap {
      translate: -5px 2px;
      font-size: 20px;
    }
    .sym_sub_text.shifted {
      translate: 10px 13px;
      font-size: 10px;
      opacity: 1.0;
    }
    .combo.sym_sub_text.tap {
      translate: -1px 1px;
    }
    .combo.sym_sub_text.shifted {
      translate: 7px 5px;
      font-size: 10px;
      opacity: 1.0;
    }

    /* Toggle */
    .toggle.shifted {
      translate: -10px 12px;
    }

    .toggle.hold {
      translate: 13px -23px;
    }

    /* Variant for tap-dances */
    .tap_dance.tap {
      translate: -7px 0px;
      font-size: 12px;
    }
    .tap_dance.shifted {
      translate: 7px 17px;
      font-size: 12px;
      opacity: 1.0;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -6px 0px;
    }
    .sym_by_sym.shifted {
      translate: 10px 12px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.tap {
      translate: -35px 0px;
    }
    .combo.sym_by_sym.shifted {
      translate: 35px 20px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.hold {
      visibility: hidden;
    }

    /* hide hold box for combo sym_by_sym */
    .combo.sym_by_sym.hold > path[stroke="none"][fill="none"] {
      visibility: hidden;
    }

  shrink_wide_legends: 6
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs: 
    shift_copy: |
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="1000" height="1000" viewBox="0 0 1000 1000" xml:space="preserve">
        <desc>Created with Fabric.js 3.5.0</desc>
        <defs>
        </defs>
        <rect x="0" y="0" width="100%" height="100%" fill="#ffffff"/>
        <g transform="matrix(0.8382 0 0 0.8382 781.3816 453.9535)" id="301966">
        <path style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; is-custom-font: none; font-file-url: none; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" vector-effect="non-scaling-stroke" transform=" translate(-320, -320)" d="M 480 400 L 288 400 C 279.2 400 272 392.8 272 384 L 272 128 C 272 119.2 279.2 112 288 112 L 421.5 112 C 425.7 112 429.8 113.7 432.8 116.7 L 491.3 175.2 C 494.3 178.2 496 182.3 496 186.5 L 496 384 C 496 392.8 488.8 400 480 400 z M 288 448 L 480 448 C 515.3 448 544 419.3 544 384 L 544 186.5 C 544 169.5 537.3 153.2 525.3 141.2 L 466.7 82.7 C 454.7 70.7 438.5 64 421.5 64 L 288 64 C 252.7 64 224 92.7 224 128 L 224 384 C 224 419.3 252.7 448 288 448 z M 160 192 C 124.7 192 96 220.7 96 256 L 96 512 C 96 547.3 124.7 576 160 576 L 352 576 C 387.3 576 416 547.3 416 512 L 416 496 L 368 496 L 368 512 C 368 520.8 360.8 528 352 528 L 160 528 C 151.2 528 144 520.8 144 512 L 144 256 C 144 247.2 151.2 240 160 240 L 176 240 L 176 192 L 160 192 z" stroke-linecap="round"/>
        </g>
        <g transform="matrix(26.0791 0 0 26.0791 284.7443 448.0071)" id="275956">
        <path style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; is-custom-font: none; font-file-url: none; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" vector-effect="non-scaling-stroke" transform=" translate(-12, -12)" d="M 15 18 V 12 H 17.17 L 12 6.83 L 6.83 12 H 9 V 18 H 15 M 12 4 L 22 14 H 17 V 20 H 7 V 14 H 2 L 12 4 Z" stroke-linecap="round"/>
        </g>
      </svg>
    2_bluetooth : |
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="940" height="788" viewBox="0 0 940 788" xml:space="preserve">
        <desc>Created with Fabric.js 3.5.0</desc>
        <defs>
        </defs>
        <rect x="0" y="0" width="100%" height="100%" fill="#ffffff"/>
        <g transform="matrix(1 0 0 1 251.0574 450.1346)" style="" id="744513">
            
        <path xml:space="preserve" font-family="Lato" font-size="612" font-style="normal" font-weight="bold" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; is-custom-font: none; font-file-url: none; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1; white-space: pre;" d="M0.36-255.12L0.36-255.12Q30.96-255.12 56.36-246.09Q81.75-237.06 99.81-220.54Q117.86-204.02 127.96-180.76Q138.06-157.50 138.06-129.05L138.06-129.05Q138.06-104.57 130.87-83.76Q123.67-62.95 111.59-43.98Q99.50-25.01 83.28-7.26Q67.06 10.49 49.32 28.85L49.32 28.85L-50.44 130.75Q-35.75 126.46-21.67 124.17Q-7.60 121.87 5.25 121.87L5.25 121.87L118.78 121.87Q131.02 121.87 138.21 128.76Q145.40 135.64 145.40 146.97L145.40 146.97L145.40 192.25L-158.15 192.25L-158.15 167.16Q-158.15 159.51-154.94 151.25Q-151.72 142.99-144.69 135.95L-144.69 135.95L-10.35 1.31Q6.48-15.83 19.79-31.43Q33.10-47.04 42.13-62.34Q51.15-77.64 55.90-93.40Q60.64-109.16 60.64-126.60L60.64-126.60Q60.64-142.51 56.05-154.60Q51.46-166.68 42.89-174.95Q34.32-183.21 22.54-187.34Q10.76-191.47-3.93-191.47L-3.93-191.47Q-31.16-191.47-48.76-177.70Q-66.35-163.93-73.39-140.67L-73.39-140.67Q-76.75-129.05-83.49-124.00Q-90.22-118.95-100.62-118.95L-100.62-118.95Q-105.21-118.95-110.72-119.87L-110.72-119.87L-150.50-126.90Q-145.91-158.73-132.75-182.75Q-119.59-206.77-99.86-222.84Q-80.12-238.90-54.57-247.01Q-29.02-255.12 0.36-255.12Z"/></g>
        <g transform="matrix(22.6514 0 0 22.6514 664.7828 420.4343)" id="777287">
        <path style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; is-custom-font: none; font-file-url: none; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" vector-effect="non-scaling-stroke" transform=" translate(-11.355, -12)" d="M 14.88 16.29 L 13 18.17 V 14.41 M 13 5.83 L 14.88 7.71 L 13 9.58 M 17.71 7.71 L 12 2 H 11 V 9.58 L 6.41 5 L 5 6.41 L 10.59 12 L 5 17.58 L 6.41 19 L 11 14.41 V 22 H 12 L 17.71 16.29 L 13.41 12 L 17.71 7.71 Z" stroke-linecap="round"/>
        </g>
      </svg>
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true

parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:
    # Example: '': {s: "", h: "", t: ""}   '': {s: "", h: "", t: "$$mdi:$$"}

    # Function Layer Left
    '&deae':  {s: "Ä", h: "ä", t: "$$mdi:content-cut$$"}
    '&kp LC(F)': {s: "", h: "", t: "$$mdi:file-find-outline$$"}
    '&hmr LC(LS(C)) LC(C)': {s: "", h: "$$shift_copy$$", t: "$$mdi:content-copy$$"}
    '&hmr LC(LS(V)) LC(V)': {s: "", h: "", t: "$$mdi:content-paste$$"}
    '&kp LC(Z)': {s: "", h: "", t: "$$mdi:undo$$"}
    '&kp LC(Y)': {s: "", h: "", t: "$$mdi:redo$$ "}
    '&kp LC(R)': {s: "", h: "", t: "$$mdi:web-refresh$$"}
    '&kp LC(K)': {s: "", h: "", t: "$$mdi:search-web$$"}
    '&kp LC(MINUS)': {s: "", h: "", t: "$$mdi:magnify-minus-outline$$"}
    '&kp LC(PLUS)': {s: "", h: "", t: "$$mdi:magnify-plus-outline$$"}
    '&kp HOME': {s: "", h: "", t: "$$mdi:home$$"}
    
    #  Function Layer Right
    '&deuo': {s: "Ü", h: "", t: "t"}
    '&deue': {s: "Ü", h: "ü", t: "$$2_bluetooth$$"}
    '&kp K_MUTE': {s: "", h: "", t: "$$mdi:volume-mute$$"}
    
    '&next_previous': {s: "", h: "Previous", t: "Next Song"}

    # Home Row Mods (HRM) - Display Modifiers as Subscripts
    '&hmr LEFT_WIN A': {s: "", h: "GUI", t: "A"}
    '&hmr LEFT_ALT R': {s: "", h: "ALT", t: "R"}
    '&hmr LCTRL S': {s: "", h: "CTRL", t: "S"}
    '&hmr RCTRL E': {s: "", h: "CTRL", t: "E"}
    '&hmr RIGHT_ALT I': {s: "", h: "ALT", t: "I"}
    '&hmr RIGHT_WIN O': {s: "", h: "GUI", t: "O"}
    # Layers
    "&ltq 1 BACKSPACE":
      tap:  $$mdi:backspace$$
      hold: '$$mdi:navigation-variant$$'
    "&ltq 3 TAB":
      tap: $$mdi:keyboard-tab$$
      hold: $$mdi:numeric$$
    "&ltq 2 SPACE":
      tap: $$mdi:keyboard-space$$
      hold: $$mdi:symbol$$
    "&ltq 3 ENTER":
      tap: $$mdi:keyboard-return$$
      hold: $$mdi:numeric$$
    "&ltq 1 DELETE":
      tap: $$mdi:backspace-reverse-outline$$
      hold: $$mdi:navigation-variant$$
    # Home rows
    "&hm LEFT_GUI A":
      tap: 'A'
      shifted: $$mdi:apple-keyboard-command$$
    "&hm LEFT_ALT S":
      tap: 'S'
      shifted: $$mdi:apple-keyboard-option$$
    "&hm LEFT_CONTROL D":
      tap: 'D'
      shifted: $$mdi:apple-keyboard-control$$
    "&hm LEFT_SHIFT F":
      tap: 'F'
      shifted: $$mdi:apple-keyboard-shift$$
    "&hm RIGHT_SHIFT J":
      tap: 'J'
      shifted: $$mdi:apple-keyboard-shift$$
    "&hm RIGHT_CONTROL K":
      tap: 'K'
      shifted: $$mdi:apple-keyboard-control$$
    "&hm RIGHT_ALT L":
      tap: 'L'
      shifted: $$mdi:apple-keyboard-option$$
    # self behaviors
    "&hm LG(LS(V)) P":
      tap: 'P'
      shifted: $$mdi:content-copy$$
    # Mouse
    "&msc SCRL_UP":
      tap: $$mdi:pan-up$$
      hold: ''
      shifted: ''
    "&msc SCRL_DOWN":
      tap: $$mdi:pan-down$$
      hold: ''
      shifted: ''
    "&msc SCRL_LEFT":
      tap: $$mdi:pan-left$$
      hold: ''
      shifted: ''
    "&msc SCRL_RIGHT":
      tap: $$mdi:pan-right$$
      hold: ''
      shifted: ''
    "&mmv MOVE_LEFT":
      tap: $$mdi:menu-left$$
      hold: ''
      shifted: $$mdi:mouse$$
    "&mmv MOVE_RIGHT":
      tap: $$mdi:menu-right$$
      hold: ''
      shifted: $$mdi:mouse$$
    "&mmv MOVE_UP":
      tap: $$mdi:menu-up$$
      hold: ''
      shifted: $$mdi:mouse$$
    "&mmv MOVE_DOWN":
      tap: $$mdi:menu-down$$
      hold: ''
      shifted: $$mdi:mouse$$
    "&mkp LCLK":
      tap: $$mdi:mouse-left-click-outline$$
    "&mkp RCLK":
      tap: $$mdi:mouse-right-click-outline$$
    "&mkp MCLK":
      tap: $$mdi:mouse-scroll-wheel$$
    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$
    "&kt RSHIFT":
      tap: $$mdi:apple-keyboard-shift$$
      hold: $$mdi:toggle-switch$$

    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none

    # Whitespace
    "&bkspc_del":
      type: backspace
      tap: $$mdi:backspace$$
      shifted: $$mdi:backspace-reverse-outline$$

    # Bluetooth
    "&bt BT_SEL 0":
      {s: $$mdi:bluetooth$$, t: $$mdi:numeric-1$$}
    "&bt BT_SEL 1":
      {t: $$mdi:bluetooth$$, h: $$mdi:numeric-2$$}
    "&bt BT_SEL 2":
      {s: $$mdi:bluetooth$$, t: $$mdi:numeric-3$$}
    "&bt BT_SEL 3":
      {s: $$mdi:bluetooth$$, t: $$mdi:numeric-4$$}
    "&bt BT_SEL 4": {s: $$mdi:bluetooth$$, t: $$mdi:numeric-5$$}
      
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
    "&bt BT_PRV":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:arrow-up-bold$$
    "&bt BT_NXT":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:arrow-down-bold$$
    # Reset
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$

  # ZMK
  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: "="
      shifted: "+"
    PLUS: +
    MINUS:
      tap: "-"
      shifted: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'

    LESS_THAN: <
    LT: <
    PERIOD: '.'
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # Numbers
    N1:
      tap: 1
      shifted: "!"
    N2:
      tap: 2
      shifted: "@"
    N3:
      tap: 3
      shifted: "#"
    N4:
      tap: 4
      shifted: "$"
    N5:
      tap: 5
      shifted: "%"
    N6:
      tap: 6
      shifted: "^"
    N7:
      tap: 7
      shifted: "&"
    N8:
      tap: 8
      shifted: "*"
    N9:
      tap: 9
      shifted: "("
    N0:
      tap: 0
      shifted: ")"

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    LG: $$mdi:apple-keyboard-command$$
    LEFT_GUI: $$mdi:apple-keyboard-command$$
    LEFT_COMMAND: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    RG: $$mdi:apple-keyboard-command$$
    PSCRN: $$mdi:printer-outline$$
    RIGHT_COMMAND: $$mdi:apple-keyboard-command$$
    PAGE_UP:
      tap: 'PgUp'
      shifted: ''
    PAGE_DOWN:
      tap: 'PgDn'
      shifted: ''
    INSERT:
       tap: 'Ins'
       shifted: ''
    # "Meh" key
    LS(LC(LALT)): $$mdi:star-three-points$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    UP_ARROW: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    DOWN_ARROW: $$mdi:arrow-down-bold$$
    LEFT_ARROW: $$mdi:arrow-left-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    RIGHT_ARROW: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    ESCAPE: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_VOLUME_DOWN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRIGHTNESS_INC: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$
    C_BRI_DEC: $$mdi:brightness-7$$
    C_BRIGHTNESS_DEC: $$mdi:brightness-7$$

    # System
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$
    K_FIND: $$mdi:apple-finder$$
    # Command + 
    LG(A):
      tap: 'A'
      hold: $$mdi:apple-keyboard-command$$
    LG(S):
      tap: 'S'
      hold: $$mdi:apple-keyboard-command$$
    LG(D):
      tap: 'D'
      hold: $$mdi:apple-keyboard-command$$
    LG(F):
      tap: 'F'
      hold: $$mdi:apple-keyboard-command$$
    LG(Z):
      tap: 'Z'
      hold: $$mdi:apple-keyboard-command$$
    LG(X):
      tap: 'X'
      hold: $$mdi:apple-keyboard-command$$
    LG(C):
      tap: 'C'
      hold: $$mdi:apple-keyboard-command$$
    LG(V):
      tap: 'V'
      hold: $$mdi:apple-keyboard-command$$
    # Zoom
    RG(RS(A)):
      tap: $$mdi:microphone$$
      hold: zoom
    RG(RS(V)):
      tap: $$mdi:video$$
      hold: zoom

  zmk_combos:
    combo_to_2:
      align: top
    combo_to_3:
      align: top
    combo_bt_clear:
      align: top
      offset: 0.03
    combo_mute:
      align: top
      offset: 0.15
    combo_minus:
      key:
        shifted: "_"
        hold: "-"
    combo_equal:
      key:
        shifted: "+"
        hold: "="
    combo_backslash:
      key:
        shifted: "|"
        hold: \
    combo_lbkt:
      key:
        shifted: "{"
        hold: "["
    combo_rbkt:
      key:
        shifted: "}"
        hold: "]"
    combo_semicolon:
      key:
        shifted: ":"
        hold: ";"
