name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
    
    env:
      BUILDING_FIRMWARE: "1"  # This defines the variable for the build process
